version: '3'

services:
  frontend:
    build: ./websockets/ # specify the directory of the Dockerfile
    ports:
      - "4200:4200" #specify ports forewarding
      - "49153:49153"
    expose:
      - "4200"
      - "49153"
    command: npm run dockerStart
    volumes:
      - ./websockets/:/code
  server:
      build: ./server/ # specify the directory of the Dockerfile
      ports:
        - "3001:3001" #specify ports forewarding
      expose:
        - "3001"
      command: go run /go/src/chatapp/main.go /go/src/chatapp/client.go /go/src/chatapp/hub.go
      volumes:
        - ./server/:/go/src/chatapp
      depends_on:
        - database
  
  database: # name of the third service
    image: mongo:latest # specify image to build container from
    container_name: crmmongo
    volumes:
      - crmmongo:/data/db
    ports:
      - "27017:27017" # specify port forewarding
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: crm
    
volumes:
  crmmongo: